### ISSUE TITLE
Grid Klassen werden bei Formularfeld Submit nicht angefügt.

### ISSUE THREAD

**Issue by digitalingenieur** [ErdmannFreunde/euf_grid#1]
Beim Anfügen der Grid-Klassen in Formularen, wird der Submit-Button ignoriert.

Schuld daran ist GridHooks.php Zeile 141
Dort müsste es heißen:
`if ($objWidget->type === 'fieldset' || $objWidget->type==='submit') `

Viele Grüße
Samuel Heer

**Comment by denniserdmann** [comment]
Moin Samuel,

stimmt, der Button wird aktuell nicht berücksichtigt. Deine Anpassung führte bei mir allerdings dazu, dass die Klasse sowohl für den `<div class="submit_container>` als auch für `<input class="submit">` vergeben wird. Das müssen wir uns bei Gelegenheit mal genauer ansehen.

In der Zwischenzeit kannst du dir zur Not mit einem zusätzlichen Spalten-Container behelfen.

**Comment by bastibuck** [comment]
Hey Samuel,

danke für die saubere und hilfreiche Beschreibung des Bugs und die gleichzeitige Lösung :-) 

Die Ausgabe am Container sowie dem Button kann man nur über das Template ändern, oder ein entsprechendes CSS verwenden.

Danke und besten Gruß
