### ISSUE TITLE
Update-Hinweis aktualisieren

### ISSUE THREAD

**Issue by fkaminski** [ErdmannFreunde/euf_grid#13]
Hallo,
Vielen Dank für die Erweiterung.

Ich habe nur zufällig euren Beitrag gelesen:
https://erdmann-freunde.de/logbuch/grid-erweiterung-version-3/

Könntet Ihr bitte den Update-Hinweis hier bez. der Version 3 ( CSS-Grid ) aktualisieren.

**Comment by denniserdmann** [comment]
Moin @fkaminski,
vielen Dank für das Ticket. Ich habe den Update-Hinweis entsprechend angepasst.
