### ISSUE TITLE
Wo Breakpoint ändern?

### ISSUE THREAD

**Issue by Shoekrates** [ErdmannFreunde/euf_grid#14]
Hallo,
stehe gerade etwas auf dem Schlauch. Wo kann ich denn die Werte der Breakpoints updatesicher ändern? Geht das überhaupt?
Ich habe auch in der Doku (außer in der CSS-Datei selbst) keine Übersicht der bestehenden Breakpoints gefunden. Das sind die Werte aus der CSS-Datei.
SM = 34.375em (entspricht 550px)
MD = 48em (768px)
LG = 58.75em (940px)
XL = 68.75em (1100px)

**Comment by denniserdmann** [comment]
Moin Christian,

die Breakpoints lassen sich in der CSS-Datei aktuell nicht ändern. Wir sind bisher davon ausgegangen, dass man sich dann selbst eine Grid-Datei erstellt. 

Aber … DAS wäre eine gutes Einsatzgebiet für die Verwendung von Custom Properties. Ich werde mal schauen, ob ich das morgen unter bekomme.

**Comment by denniserdmann** [comment]
Schade, schade. Leider lassen sich Custom Properties nicht als Breakpoints definieren, siehe auch https://www.mediaevent.de/css/variable.html

> In Media Queries können Custom Properties nicht verwendet werden. Die CSS Variable im Beispiel gilt für :root, also das html-Element, und wird an andere Elemente vererbt.

Somit bleibt nur der Weg, eine eigene CSS-Datei für das Grid einzubinden.

**Comment by Shoekrates** [comment]
Ah, das ist schade. 
OK, dann geht es halt über ein eigenes SASS-Partial mit entsprechenden Variablen.
Danke für deine Mühen.
