### ISSUE TITLE
Contao 3.5 keine Checkbox im Layout für EuF Grid CSS 

### ISSUE THREAD

**Issue by Ainschy** [ErdmannFreunde/euf_grid#15]
Moin,
ich liebe diese Erweiterung und wollte sie in einem 3.5er Projekt einsetzten. 

Jedoch vermisse ich dort im Layout die Checkbox zum hinzufügen der CSS-Datei. Habs für mich manuell gelöst aber ich denke so sollte es nicht sein.

**Comment by denniserdmann** [comment]
Moin @Ainschy,
danke für den Hinweis. Das ist höchstwahrscheinlich im Zuge der Optimierung für Contao 4.8 passiert, siehe https://github.com/ErdmannFreunde/euf_grid/commit/c8d19dff4feffd9ebcd2365eeb261f748035d2ad

Theoretisch hätten wir die Systemvoraussetzung auf Contao 4 anheben können, da Contao 3.5 ja nun so langsam aussterben wird. Da die Erweiterung aber abgesehen davon noch funktioniert, ist das vielleicht nicht solo schlimm. Was meinst du? cc @richardhj

**Comment by richardhj** [comment]
Upps, tatsächlich gibt es das Feld `combineScripts` nicht in Contao 3.5. 
Über PhpMyAdmin lässt sich das aktiveren. Das passt doch, wenn man bedenkt, dass Contao 3 EOL ist?

**Comment by Ainschy** [comment]
Bis auf die fehlende Checkbox läuft die Erweiterung wie gewünscht. Ich würde es so lassen und einen Hinweis zur manuellen Einbinden der CSS Datei ins Readme setzen.

**Comment by denniserdmann** [comment]
Habe die Hinweise ergänzt
