### ISSUE TITLE
Version 3.1 und IE11

### ISSUE THREAD

**Issue by ghost** [ErdmannFreunde/euf_grid#16]
Habe die Version 3.1 installiert. Mit IE11 (leider immer noch etwas Marktanteil) wird die Darstellung aber völlig massakriert.
Gibt es da von eurer Seite noch CSS-Anpassung oder lasst ihr es bewusst bleiben? Letzteres würde ich verstehen ;-).

**Comment by denniserdmann** [comment]
Für Projekte erweitern wir die Angaben noch um ein paar Fixes, aber Erweiterung selbst wird keine IE11 Unterstützung mehr anbieten. Hier muss man auch von Fall zu Fall entscheiden, wie die Fallback-Lösung aussehen kann.

**Comment by ghost** [comment]
Hallo Dennis

Danke für die schnelle Antwort! Alles klar, dann werde ich das mal in Angriff nehmen!
