### ISSUE TITLE
Include Spacing

### ISSUE THREAD

**Issue by katgirl** [ErdmannFreunde/euf_grid#18]
Assign responsive-friendly margin or padding values to an element or a subset of its sides with shorthand classes. Includes support for individual properties, all properties, and vertical and horizontal properties. Classes are built from a default Sass map ranging from .25rem to 3rem.

See: https://getbootstrap.com/docs/4.0/utilities/spacing/

**Comment by denniserdmann** [comment]
I think, what you're looking for is a general utility-classes extension (so instead of writing css classes by yourself, you can choose from a predefined set). 

But as euf_grid is just for grid-layouts, i will close this issue (and think about a separate extension)
