### ISSUE TITLE
Include SCSS Source

### ISSUE THREAD

**Issue by bezin** [ErdmannFreunde/euf_grid#21]
Hello, 

we use your grid extension again in a recent project – thanks for sharing! 
Is there a SCSS basis with variables for the CSS? If yes, would it be possible to include this as well? 

This would help with breakpoints as we could include the SCSS source files and a predefined breakpoint map.

Stay healthy!

**Comment by denniserdmann** [comment]
Not at the moment. But that's a good idea.

I will add an example file for the new [contao-grid-bundle](https://github.com/ErdmannFreunde/contao-grid-bundle) in the following weeks. You could use it for euf_grid as well.

**Comment by bezin** [comment]
Oh, I haven't seen that other bundle. I am gonna migrate right away. I can also provide a PR as I will use my own SCSS file based on your CSS anyways?

**Comment by denniserdmann** [comment]
sure

**Comment by bastibuck** [comment]
Sounds like a great idea :) 
👍

**Comment by bezin** [comment]
Closing here, will continue in https://github.com/ErdmannFreunde/contao-grid-bundle/issues/1
