### ISSUE TITLE
Problem with heimrichhannot/contao-teaser-bundle

### ISSUE THREAD

**Issue by deralteherr** [ErdmannFreunde/euf_grid#22]
Hi,
when I add a Link-Teaser Element by heimrichhannot/contao-teaser-bundle V 1.1.4, no Grid-Einstellungen »Grid Colums & Rows« and »Grid Optinon« are added to the Element.
euf_grid V 3.1.0,
CONTAO 4.11.3
I dont know wether heimrichhannot/contao-teaser-bundle makes the trouble or euf-grid.
Sencerely
Rudolf

**Comment by denniserdmann** [comment]
Hey Rudolf,

this is a known problem. Some extensions may not have the grid-settings. In this case, you have to use the column start and end element to wrap your not supported element.

I also encourage you to check out the [contao-grid-bundle](https://github.com/ErdmannFreunde/contao-grid-bundle), which is the replacement for euf_grid. Maybe you have more luck with it.
