### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by michaelgawlik** [ErdmannFreunde/euf_grid#23]
Liebes Entwicklerteam,

ich bekomme beim Speichern eines Elements folgenden Fehler:

`Uncaught PHP Exception TypeError: "implode(): Argument #2 ($array) must be of type ?array, string given" at .../contao/vendor/erdmannfreunde/euf_grid/classes/GridClass.php line 149`

Contao: 4.9
EUF_Grid: 3.1.0

Ich habe diese Kombination schon mehrfach eingesetzt, der einzige Unterschied ist PHP 8.0

Danke Euch

**Comment by denniserdmann** [comment]
Moin Michael,
die euf_grid Erweiterung wird nicht mehr weiterentwickelt, da sie von https://github.com/ErdmannFreunde/contao-grid-bundle abgelöst wird. Da du die Version 3.1 verwendest, sollte ein Wechsel von euf_grid zu contao-grid-bundle ohne größere Probleme möglich sein (Backup würde ich trotzdem zur Sicherheit machen).

Sollte der Fehler bei beim Grid Bundle ebenfalls auftauchen, würde ich dich bitten dort ein Ticket zu erstellen.

**Comment by michaelgawlik** [comment]
Ein Traum - es funktioniert ohne Probleme.

Vielen Dank.
