### ISSUE TITLE
Missing ID in FE elements

### ISSUE THREAD

**Issue by bastibuck** [ErdmannFreunde/euf_grid#3]
Adding a ID in backend via the ID/Class fields doesn't print the ID in FE.

**Comment by denniserdmann** [comment]
Row-Element, Column-Element or both? 

Had a similar problem, when trying to add space via the _space before_ and _space after_ fields.

**Comment by bastibuck** [comment]
Only tested row-element. But could be both. Will check later

**Comment by bastibuck** [comment]
Fixed in 2.0.1
