### ISSUE TITLE
Grid CSS in Contao 4 verfügbar machen

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/euf_grid#4]
Aktuell wird die Grid CSS-Datei in Contao 4 nicht geladen, da sich die Ordnerstruktur geändert hat.

**Comment by denniserdmann** [comment]
Da externe CSS-Dateien sich offenbar nicht mehr in die Liste *CSS-Framework* einfügen lassen, schlage ich vor, dass wir eine Checkbox unterhalb von *Externe Stylesheets* einfügen, mithilfe man die CSS laden kann.

**Comment by bastibuck** [comment]
Fixed and tested in https://github.com/ErdmannFreunde/euf_grid/commit/43b56cb96fab37797691c8a94bb117aba4b07f8d
