### ISSUE TITLE
Zusätzliche Grid-Klassen werden im BE nicht angezeigt 

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/euf_grid#5]
Eingabemaske:
![bildschirmfoto 2017-05-26 um 09 23 54](https://cloud.githubusercontent.com/assets/3773697/26484925/14ec3de2-41f5-11e7-8acd-79cef52606e5.png)

BE-Ansicht:
![bildschirmfoto 2017-05-26 um 09 24 28](https://cloud.githubusercontent.com/assets/3773697/26484948/2cc238d6-41f5-11e7-88b3-664aaf1870b8.png)

**Comment by bastibuck** [comment]
Fixed in b34dbc70adb1bff893f8d4c3672cd7744eec53d4
