### ISSUE TITLE
Add current content element to hook signature

### ISSUE THREAD

**Issue by bezin** [ErdmannFreunde/euf_grid#7]
Hello there :)

first of all thanks for this extension. @bastibuck told me about the "manipulateGridClasses" hook at the Contao Camp that might be leveraged to add more custom css classes. However, in my eyes the hook signature is missing one important argument, i.e. the current content element (https://github.com/ErdmannFreunde/euf_grid/blob/master/classes/GridHooks.php#L57)

If you would pass this done to the hook, one might be able to dynamically append css classes per content element to the surrounding div that is created here: https://github.com/ErdmannFreunde/euf_grid/blob/master/classes/GridHooks.php#L78

I am building a 3×3 masonry grid layout and this small change is the difference between 
"Row Start, 9 Custom Elements, Row End" (11 content elements)  and 
"Row Start, {Column Start, Custom Element, Column End}×9, Row End" (29 content elements). 

This would save plenty of time creating and editing the content as well as giving more flexibility to devs :)

If you agree, I could prepare a PR.

Cheerio

EDIT: To be more precisely, one can achieve the 11 CE setup with the grid_options field as well, but then the editor has to select a couple of classes every time. That is what I would like to do programmatically.

**Comment by bastibuck** [comment]
Hey,

I see what you want to achieve and your solutions sounds good to me. It won't hurt anyone I believe if the current CE is added and - as you said - adds more flexibility to developers.

The callback hook would need to be changed to something like this on all calls:
`$class = $this->{$callback[0]}->{$callback[1]}($env, $strField, $class, $objElement);`

What does @denniserdmann think?

Cheers and thanks for your input

----
PS: Now that I see the code again it looks like we could improve in code quality quite a lot 😆

**Comment by denniserdmann** [comment]
Go for it!

**Comment by bezin** [comment]
Hi there, 

[I started working on it and did some refactoring to the GridHooks->addGridClasses method](https://github.com/presprog/euf_grid/commits/feature/addCEtoHookSignature) to simplify it a little. I applied the refactoring in small commits so it is easier to check. I also added the current content element already – however there is one issue:

The hook gets called only if there is at least one css class given (either grid_columns or grid_options). If the editor does not add at least one class, the dev cannot add classes as he wishes. 

In my opinion, the callback should be called at least once anyways. But this means we we would need to change the implementation a little :/ I am not sure whether this affects backwards compatibility.

**Comment by bastibuck** [comment]
Awesome, like your changes! Only checked in webview so far though.

I think if neither **grid_columns** nor **grid_options** is set on an element we shouldn't call our callback since it is not connected to the grid-extension in any way. It would be called for all CEs, right?

I'd rather use a custom hook in this case than adding a mandatory call of this hook for each element from our extension. 
What do you think?

**Comment by denniserdmann** [comment]
Hey @bezin, was machen wir denn aus deinem Ticket? Ist das noch aktuell?

**Comment by bezin** [comment]
Oh, and by the way: As @bastibuck was totally right in his comment, this is obviously obsolete 🙈
