### ISSUE TITLE
Contao 4: Grid classes are applied twiced on submit buttons

### ISSUE THREAD

**Issue by bezin** [ErdmannFreunde/euf_grid#8]
Hello there,

when adding grid classes to a form submit button, the classes get applied twice on the widget div and the input itself (as @denniserdmann mentioned in #1 already). 

As far as I see, there is no need to handle the submit button any differently than other fields (except fieldset). You just set the grid classes on $this->prefix and it works as expected. Basically, [you revert the changes made in GridHooks in commit d0e10a](https://github.com/ErdmannFreunde/euf_grid/commit/d0e10aeb367b23f2bd179a5a0e7136388a3d0346#diff-d197913d45a77dcffae37dac4a397008R141). 

This means as well, that I cannot reproduce issue #1. When I revert the mentioned line, it works perfectly. 

Cheerio

**Comment by denniserdmann** [comment]
Might be a difference if you use Contao 3 or 4, but haven't tested it. Which Contao Version do you use? As Contao 4 now uses a <button> Element instead of an input, there could be other changes aswell.

**Comment by bezin** [comment]
Ah yeah, you are totally right, I did not remember this change. I am using it with Contao 4.4 LTS, but I just tested it with Contao 3 as well. With C3 I can reproduce #1 – the mentioned changes are needed to fix this, but they are not necessary for C4. So we would have to implement a version specific solution or maintain two versions of euf_grid.

**Comment by denniserdmann** [comment]
Is this a legit way to check whether Contao 3 or 4 ist used? 

`if (method_exists('Contao\System', 'getContainer')) { }`

[see here](https://github.com/isotope/core/blob/master/system/modules/isotope/drivers/DC_TablePageId.php#L1580)

**Comment by bezin** [comment]
I think we should just use ```if (version_compare(VERSION, '4.0', '>=')) { [...] }``` :)

**Comment by bastibuck** [comment]
Agreed!
